### ISSUE TITLE
ModelAttribute 와 RequestBody 의 차이점

### ISSUE THREAD

**Issue by Dendroh** [nhnacademy-be3-CookShoong/issue-manage#173]
RequestBody 의 역할은 요청 본문의 JSON, XML, TEXT 등의 데이터를 적합한 HttpMessageConverter 를 통해 파싱하여 Java 객체로 변환하는 것입니다.
RequestBody 를 사용할 객체는 필드를 바인딩할 생성자나 setter 메서드가 필요가 없으나, 직렬화를 위한 기본 생성자를 필수적으로 요구합니다.

ModelAttribute 의 역할은 Http 파라미터 데이터를 Java 객체에 맵핑하는 것입니다.
ModelAttribute 를 사용할 때는 객체의 필드에 접근해 데이터를 바인딩하는 생성자 또는 setter 메서드를 필요로 합니다.

**Comment by 10kseok** [comment]
DTO
Request DTO : `getter` 와 `기본생성자` 필요
Response DTO : `getter` 필요
