### ISSUE TITLE
템플릿 공유

### ISSUE THREAD

**Issue by Dendroh** [nhnacademy-be3-CookShoong/issue-manage#18]
https://tabler.io/

**Comment by eora21** [comment]
# 무료 템플릿 사이트
- https://startbootstrap.com/?showPro=false&showAngular=false&showVue=false
- https://themewagon.com/theme-framework/bootstrap-5/?swoof=1&pa_price=free&paged=1&really_curr_tax=28-pa_frameworks
- https://bootstrapmade.com/

**Comment by JeongJeWan** [comment]
https://themewagon.com/?s=food&post_type=product

**Comment by JeongJeWan** [comment]
https://themewagon.github.io/foodwagon/v1.0.0/

**Comment by Dendroh** [comment]
https://themewagon.com/themes/template-collection-2022-one-hundred-free-html5-templates-in-one-bundle/

**Comment by Dendroh** [comment]
https://themewagon.com/themes/template-collection-2023-hundred-pre-built-websites-for-free/

**Comment by Dendroh** [comment]
2023 버전의 템플릿 예시들을 업로드 하였습니다. 프론트 페이지 작성시 참고할만한 html 부분을 복사할 때 사용할 수 있습니다. 각 html 코드는 Boot Strap 5 를 지원하는 코드를 사용해야 합니다.

**Comment by Dendroh** [comment]
새로 합의된 사항으로 인해 이슈를 닫습니다.
